version: "3"

services:
  api:
    image: apico2emission
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000

  website:
    image: websiteco2emission
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000