version: "3"

services:
  api:
    image: flaskapp
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src

  website:
    image: flaskapp
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src