name: pytorchcpu
channels:
  - pytorch
  - defaults
dependencies:
  - blas=1.0
  - bottleneck=1.3.5
  - bzip2=1.0.8
  - ca-certificates=2022.10.11
  - certifi=2022.12.7
  - click=8.0.4
  - colorama=0.4.6
  - cpuonly=2.0=0
  - flask=2.2.2
  - flask_cors=3.0.10
  - flit-core=3.6.0
  - intel-openmp=2021.4.0
  - itsdangerous=2.0.1
  - jinja2=3.1.2
  - libffi=3.4.2
  - libuv=1.40.0
  - markupsafe=2.1.1
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - numexpr=2.8.4
  - numpy=1.23.5
  - numpy-base=1.23.5
  - openssl=1.1.1s
  - packaging=22.0
  - pandas=1.5.2
  - pip=22.3.1
  - python=3.10.9
  - python-dateutil=2.8.2
  - pytorch=1.13.1
  - pytorch-mutex=1.0=cpu
  - pytz=2022.7
  - setuptools=65.6.3
  - six=1.16.0
  - sqlite=3.40.1
  - tk=8.6.12
  - typing_extensions=4.4.0
  - tzdata=2022g
  - werkzeug=2.2.2
  - wheel=0.37.1
  - xz=5.2.10
  - zlib=1.2.13

